# Generated by Django 3.2.8 on 2021-10-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(blank=True, max_length=40, primary_key=True, serialize=False)),
                ('business_name', models.CharField(default='', max_length=100, verbose_name='Nombre de la empresa')),
                ('trade_name', models.CharField(default='', max_length=100, verbose_name='Nombre comercial')),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_is_valid', models.BooleanField(default=False)),
                ('nit', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Nit')),
                ('phone', models.CharField(default='', max_length=10, verbose_name='Teléfono')),
                ('phone_indicator', models.CharField(default='', max_length=4, verbose_name='Indicador')),
                ('country', models.CharField(default='', max_length=100, verbose_name='País')),
                ('state', models.CharField(default='', max_length=100, verbose_name='Departamento')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Ciudad')),
                ('web_page', models.CharField(default='', max_length=100, verbose_name='Página Web')),
            ],
        ),
    ]
